version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./exports:/app/exports
    env_file:
      - .env
    restart: unless-stopped
